travis:
  secure:
    BINSTAR_TOKEN: oRD+DK69jftJ52Uiurdmuheg+CF84pt5okMQYAGXekJxOtGnRXY2SCRsIAVhiQlZGv+9XtVSz1yP0oOom73+TcBPjsjTQGc5DHJpxP+luJ6wDu5OOqBHDbfKzcHOcPbaT/2QN/Vc2eUDrnRtlU5Kj1c0pz0dUfiHYmCuLVNpIf6gWDxzoKZG1gjCAMzny9dtwb3AyAmfLSuKxWPsvtBndk3ZZrIKrLwiJgQ+5k1h9tt8TW6jvm4b+ex+V6lj+Mns0ANKKPlrURhFyhXdjmMhkfQYnnEXxBCpjVMHFwIvSpu5I+KWqA1ZxwhR0jevOFtYkCxkQc6/Rxgq/kcCXtR6re6Aon2a/j9rDkN774KHktw56ma76b1Ip0+GWqQxbv8eCDVZ/AzGvKS2dqpnpf7QuGCyGcciz+07isoEIh+i1Lh5Hz0h+8zrPm6pnx1UQcJF0tiFWtauuPEf4CB4LIPa/EQQpngr+Dwq4jvVcQHPp3tbT+FNsJNcFCIjsOK+86vdjg0NeYfwYVnoqZtTmttnXXIAbUy4A0ikS8Yd/4GP9xDyohN2blGN3U5MkV5UXHbuoA3odozTVe/tHxNTgWdahkpjrs+x1bKTCmQXJOlbdyQXZp0Tj8U8dHivlcRVDDOM30beLTkbSuMhexGigu9b0S3UEbKVTZ6YL/Y9dG3G/Pg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
